### ISSUE TITLE
How could I change the theme?

### ISSUE THREAD

**Issue by JJBocanegra** [karingisi/syntaxed#1]
I'm looking for a change syntax theme option in OctoberCMS and in the `syntaxed` plugin path, but I can't find it.

**Comment by karingisi** [comment]
Option to change Theme is available.
When you add Component to your page. You will need to click on Syntax Component then you will see option to change Theme.
![syntaxed2](https://cloud.githubusercontent.com/assets/5733587/11318275/c4b9b5f6-909e-11e5-9de1-0cd7e8c9f254.png)

**Comment by JJBocanegra** [comment]
Thanks, could I improve the README with the info you gave me in this issues?

**Comment by karingisi** [comment]
Sure No worries. I have added you as collaborator. You can now make change and send pull request for me to merge. Any issues please let me know. Cheers
